# QQP Training Configuration
# Extends default.yaml with QQP-specific settings


dry_run: false

# Data paths
training_data_path: "datasets/tokenized/QQP-Official/train"
validation_data_path: "datasets/tokenized/QQP-Official/valid"
check_val_every_n_epoch: 5
val_interval: null

max_steps: 50000

self_consistency_ratio: 0.0

model:
  sc_rate: 0.5

# WandB configuration
wandb:
  project_name: "shortcutFM"
  run_name: "sc-0.5_shortcut-0.0-qqp"

# Checkpoint configuration
checkpoint:
  save_folder: "checkpoints/qqp/sc-0.5_shortcut-0.0-qqp"