dry_run: true
use_composer: false

model_config:
  input_dims: 768
  hidden_size: 768
  output_dims: 768
  hidden_t_dim: 128
  diffusion_steps: 2048
  min_shortcut_size: 32
  dropout: 0.1
  config_name: "bert-base-uncased"
  vocab_size: 30522
  init_pretrained: "no"
  logits_mode: 1
  sc_rate: 0.5
  predict_t: False
  max_position_embeddings: null

data_config:
  dataset_path: "override in specific config"
  batch_size: 16

training_config:
  project_name: "test"
  run_name: "SFM_v0"
  resume_wandb: "allow"

  log_interval: 1
  val_interval: 5000

  self_consistency_ratio: 0.25

  max_steps: 500
  warmup_steps: 100
  start_lr: 1e-7
  lr: 3e-4
  weight_decay: 1e-1

  gradient_clipping: 1.0
  ema:
    smoothing: 0.99
    half_life: null
    update_interval: 1

  checkpoint:
    overwrite: false
  save_folder: "checkpoints"
  save_interval: 100
  num_checkpoints_to_keep: 3

  deterministic: true
  seed: 44

