dry_run: false
use_composer: false

data_config:
  dataset_path: "datasets/tokenized/QQP-Official/train"
  accumulate_grad_batches: 8
  batch_size: 256

training_config:
  project_name: "test"
  run_name: "SFM_qqp_lit_v0.2"

  checkpoint:
    overwrite: true