# Path to training config
training_config_path: "checkpoints/qqp-simple/training_config.yaml"

# Model checkpoint and weights
checkpoint_path: "checkpoints/qqp-simple/last.ckpt"
use_ema_weights: true

# Data and batch settings
test_data_path: "datasets/tokenized/QQP-Official/test"
batch_size: 16
limit_test_batches: 2  # Set to null for all batches

# Generation settings
generation_shortcut_size: 32
output_folder: "generation_outputs/qqp"
seed: 44